name: Run Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --exitfirst  # Hace que pytest se detenga en el primer fallo

      - name: Check test status
        run: pytest | grep "collected 0 items / 1 error"
        continue-on-error: true  # Permite que el flujo de trabajo continúe incluso si los tests fallan

      - name: Set PR status
        if: failure()
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/pulls/:pull_number/merge
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.pull_request.number }}
          headers: '{"Authorization": "Bearer ${{ secrets.GITHUB_TOKEN }}"}'
          data: '{"commit_title": "Test Failed"}'
